#define STUB __attribute__((visibility("default")))

STUB void lua_atpanic(void) {}
STUB void lua_call(void) {}
STUB void lua_checkstack(void) {}
STUB void lua_close(void) {}
STUB void lua_concat(void) {}
STUB void lua_copy(void) {}
STUB void lua_cpcall(void) {}
STUB void lua_createtable(void) {}
STUB void lua_dump(void) {}
STUB void lua_equal(void) {}
STUB void lua_error(void) {}
STUB void lua_gc(void) {}
STUB void lua_getallocf(void) {}
STUB void lua_getfenv(void) {}
STUB void lua_getfield(void) {}
STUB void lua_gethook(void) {}
STUB void lua_gethookcount(void) {}
STUB void lua_gethookmask(void) {}
STUB void lua_getinfo(void) {}
STUB void lua_getlocal(void) {}
STUB void lua_getmetatable(void) {}
STUB void lua_getstack(void) {}
STUB void lua_gettable(void) {}
STUB void lua_gettop(void) {}
STUB void lua_getupvalue(void) {}
STUB void lua_insert(void) {}
STUB void lua_iscfunction(void) {}
STUB void lua_isnumber(void) {}
STUB void lua_isstring(void) {}
STUB void lua_isuserdata(void) {}
STUB void lua_isyieldable(void) {}
STUB void luaJIT_profile_dumpstack(void) {}
STUB void luaJIT_profile_start(void) {}
STUB void luaJIT_profile_stop(void) {}
STUB void luaJIT_setmode(void) {}
STUB void luaJIT_version_2_1_0_beta3(void) {}
STUB void luaL_addlstring(void) {}
STUB void luaL_addstring(void) {}
STUB void luaL_addvalue(void) {}
STUB void luaL_argerror(void) {}
STUB void luaL_buffinit(void) {}
STUB void luaL_callmeta(void) {}
STUB void luaL_checkany(void) {}
STUB void luaL_checkinteger(void) {}
STUB void luaL_checklstring(void) {}
STUB void luaL_checkstring(void) {}
STUB void luaL_checknumber(void) {}
STUB void luaL_checkoption(void) {}
STUB void luaL_checkstack(void) {}
STUB void luaL_checktype(void) {}
STUB void luaL_checkudata(void) {}
STUB void luaL_error(void) {}
STUB void lua_lessthan(void) {}
STUB void luaL_execresult(void) {}
STUB void luaL_fileresult(void) {}
STUB void luaL_findtable(void) {}
STUB void luaL_getmetafield(void) {}
STUB void luaL_gsub(void) {}
STUB void luaL_loadbuffer(void) {}
STUB void luaL_loadbufferx(void) {}
STUB void luaL_loadfile(void) {}
STUB void luaL_loadfilex(void) {}
STUB void luaL_loadstring(void) {}
STUB void luaL_newmetatable(void) {}
STUB void luaL_newmetatable_type(void) {}
STUB void luaL_newlib(void) {}
STUB void luaL_newstate(void) {}
STUB void lua_load(void) {}
STUB void lua_loadx(void) {}
STUB void luaL_openlib(void) {}
STUB void luaL_openlibs(void) {}
STUB void luaL_optinteger(void) {}
STUB void luaL_optlstring(void) {}
STUB void luaL_optnumber(void) {}
STUB void luaL_prepbuffer(void) {}
STUB void luaL_pushmodule(void) {}
STUB void luaL_pushresult(void) {}
STUB void luaL_ref(void) {}
STUB void luaL_register(void) {}
STUB void luaL_setfuncs(void) {}
STUB void luaL_setmetatable(void) {}
STUB void luaL_testudata(void) {}
STUB void luaL_traceback(void) {}
STUB void luaL_typerror(void) {}
STUB void luaL_unref(void) {}
STUB void luaL_where(void) {}
STUB void lua_newstate(void) {}
STUB void lua_newthread(void) {}
STUB void lua_newuserdata(void) {}
STUB void lua_next(void) {}
STUB void lua_objlen(void) {}
STUB void luaopen_base(void) {}
STUB void luaopen_bit(void) {}
STUB void luaopen_debug(void) {}
STUB void luaopen_jit(void) {}
STUB void luaopen_math(void) {}
STUB void luaopen_os(void) {}
STUB void luaopen_package(void) {}
STUB void luaopen_string(void) {}
STUB void luaopen_table(void) {}
STUB void lua_pcall(void) {}
STUB void lua_pushboolean(void) {}
STUB void lua_pushcclosure(void) {}
STUB void lua_pushfstring(void) {}
STUB void lua_pushinteger(void) {}
STUB void lua_pushlightuserdata(void) {}
STUB void lua_pushlstring(void) {}
STUB void lua_pushnil(void) {}
STUB void lua_pushnumber(void) {}
STUB void lua_pushstring(void) {}
STUB void lua_pushthread(void) {}
STUB void lua_pushvalue(void) {}
STUB void lua_pushvfstring(void) {}
STUB void lua_rawequal(void) {}
STUB void lua_rawget(void) {}
STUB void lua_rawgeti(void) {}
STUB void lua_rawset(void) {}
STUB void lua_rawseti(void) {}
STUB void lua_remove(void) {}
STUB void lua_replace(void) {}
STUB void lua_resume_real(void) {}
STUB void lua_setallocf(void) {}
STUB void lua_setfenv(void) {}
STUB void lua_setfield(void) {}
STUB void lua_sethook(void) {}
STUB void lua_setlocal(void) {}
STUB void lua_setmetatable(void) {}
STUB void lua_settable(void) {}
STUB void lua_settop(void) {}
STUB void lua_setupvalue(void) {}
STUB void lua_status(void) {}
STUB void lua_toboolean(void) {}
STUB void lua_tocfunction(void) {}
STUB void lua_tointeger(void) {}
STUB void lua_tointegerx(void) {}
STUB void lua_tolstring(void) {}
STUB void lua_tonumber(void) {}
STUB void lua_tonumberx(void) {}
STUB void lua_topointer(void) {}
STUB void lua_tothread(void) {}
STUB void lua_touserdata(void) {}
STUB void lua_type(void) {}
STUB void lua_typename(void) {}
STUB void lua_upvalueid(void) {}
STUB void lua_upvaluejoin(void) {}
STUB void lua_version(void) {}
STUB void lua_xmove(void) {}
STUB void lua_yield(void) {}
